# Form implementation generated from reading ui file '.\ui\rfid_tag_settings_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(258, 372)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tag_id_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.tag_id_label.setGeometry(QtCore.QRect(10, 10, 221, 16))
        self.tag_id_label.setObjectName("tag_id_label")
        self.tag_id_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tag_id_input.setGeometry(QtCore.QRect(10, 30, 241, 21))
        self.tag_id_input.setPlaceholderText("Enter RFID Tag UID")
        self.tag_id_input.setObjectName("tag_id_input")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 49, 16))
        self.label.setObjectName("label")
        self.label_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.label_input.setGeometry(QtCore.QRect(10, 80, 241, 21))
        self.label_input.setObjectName("label_input")
        self.normal_tran_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.normal_tran_button.setGeometry(QtCore.QRect(10, 150, 241, 24))
        self.normal_tran_button.setObjectName("normal_tran_button")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 130, 241, 21))
        self.label_8.setObjectName("label_8")
        self.videos_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.videos_label.setGeometry(QtCore.QRect(10, 110, 241, 21))
        self.videos_label.setObjectName("videos_label")
        self.normal_lon_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.normal_lon_button.setGeometry(QtCore.QRect(10, 190, 241, 24))
        self.normal_lon_button.setObjectName("normal_lon_button")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 170, 241, 21))
        self.label_10.setObjectName("label_10")
        self.doppler_lon_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.doppler_lon_button.setGeometry(QtCore.QRect(10, 290, 241, 24))
        self.doppler_lon_button.setObjectName("doppler_lon_button")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 270, 241, 21))
        self.label_11.setObjectName("label_11")
        self.doppler_tran_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.doppler_tran_button.setGeometry(QtCore.QRect(10, 250, 241, 24))
        self.doppler_tran_button.setObjectName("doppler_tran_button")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 230, 241, 21))
        self.label_12.setObjectName("label_12")
        self.save_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(180, 330, 75, 31))
        self.save_button.setObjectName("save_button")
        self.cancel_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(100, 330, 75, 31))
        self.cancel_button.setObjectName("cancel_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tag_id_label.setText(_translate("MainWindow", "Tag UID:"))
        self.label.setText(_translate("MainWindow", "Label:"))
        self.label_input.setPlaceholderText(_translate("MainWindow", "Enter Tag Label"))
        self.normal_tran_button.setText(_translate("MainWindow", "..."))
        self.label_8.setText(_translate("MainWindow", "Normal Transverse"))
        self.videos_label.setText(_translate("MainWindow", "Videos:"))
        self.normal_lon_button.setText(_translate("MainWindow", "..."))
        self.label_10.setText(_translate("MainWindow", "Normal Longitudinal"))
        self.doppler_lon_button.setText(_translate("MainWindow", "..."))
        self.label_11.setText(_translate("MainWindow", "Doppler Longitudinal (Optional)"))
        self.doppler_tran_button.setText(_translate("MainWindow", "..."))
        self.label_12.setText(_translate("MainWindow", "Doppler Transverse (Optional)"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))
